### ISSUE TITLE
Go back option from details page

### ISSUE THREAD

**Issue by RiverMichael** [bLangved/Pokemon-Pokedex#18]
![image](https://github.com/bLangved/Pokemon-Pokedex/assets/99018848/8ea8613f-ceeb-4111-b956-639f9ef3f0ee)

# What this issue is about:

There is no 'Go back' button/link on the Pokemon details page.

## To-do's

- [ ] Add a link/button
- [ ] Style with SCSS
- [ ] Add JS function to go back in history

## Relevant project paths (optional)

src/pages/pokemon/index.astro
src/js/selectedPokemon.js
